[project]
name = "thumbgener"
version = "0.1.6"
description = "Simple Python tool and library for generating stylish blog post thumbnails and covers"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Vlad Kudelko", email = "vlad1kudelko@gmail.com" }
]
dependencies = [
    "pillow>=12.2.0",
    "typer>=0.24.2",
]

[project.scripts]
thumbgener-cli = "thumbgener.cli:main"
