[project]
name = "thumbgener"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Vlad Kudelko", email = "vlad1kudelko@gmail.com" }
]
dependencies = [
    "pillow>=12.2.0",
    "typer>=0.24.2",
]

[project.scripts]
thumbgener-cli = "thumbgener.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/thumbgener"]

[tool.hatch.build.targets.wheel.shared-data]
"src/thumbgener/fonts" = "thumbgener/fonts"
